### PR TITLE
Correct send attachment

### PR DESCRIPTION
**Pull request by basz**
I'm trying this library with the mailgun adapter. I found I needed to adjust the format a bit when attaching attachments.

see https://documentation.mailgun.com/en/latest/api-sending.html#examples

### CODE REVIEW

**Comment by roelvanduijnhoven** [comment]
Thanks @basz. Merged, and released new version :pray:.

**Comment by basz** [comment]
Thank you Roel!

**Comment by basz** [comment]
Hi, it seems packagist is not updated... could you please do that 👍

**Comment by roelvanduijnhoven** [comment]
@basz Should be all good now! :rainbow:

**Pull request merged**
