### PR TITLE
Add an option to use only API key - header authentication

### PR DESCRIPTION
**Pull request by tdclaritum**
This PR keep backward compatibility but also allows using only the API key to authenticate the request.

### CODE REVIEW

**Comment by roelvanduijnhoven** [comment]
So you can use your username and password by setting your username as `username` , and adding your personal password to `apiKey` using the old API? Is that correct? It's not being recommended. 

We could also just remove the username option? And I'll release this as a major new version to this library? I think that is the best path forward. If you agree, can you rework your PR, and tag me once done?

**Comment by tdclaritum** [comment]
I left it there only to keep backwards compatibility but I agree the `username` and `password` should never be used. I the backward compatibility is not a problem I will remove the `username` option and will leave only the `apiKey`.

**Comment by tdclaritum** [comment]
@roelvanduijnhoven I have removed the `username` (and added `ext_json` as a requirement in the `composer.json`).

**Comment by roelvanduijnhoven** [comment]
Thanks!

What is the `ext_json` for? What part of the system uses it?

**Comment by tdclaritum** [comment]
@roelvanduijnhoven  It provides all JSON methods [JSON Functions](https://www.php.net/manual/en/ref.json.php). It is used in all integrations.

**Comment by roelvanduijnhoven** [comment]
Lol did not know that! Useful addition :D.

**Comment by roelvanduijnhoven** [comment]
Version v5.0 is out. Please do test, and let me know if any bugs pop up :).

**Pull request merged**
